-- ==============================================================
-- ESQUEMA DE BASE DE DATOS SUPABASE (PostgreSQL)
-- PARA BOT AMBIENTE TUCUMÁN
-- ==============================================================

-- 1. Tabla de Historial de Chat (Memoria LangChain)
CREATE TABLE public.chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para búsqueda rápida por sesión
CREATE INDEX idx_chat_history_session_id ON public.chat_history (session_id);

-- 2. Tabla de Tickets (Retiros Especiales y Reclamos de Recolección)
CREATE TABLE public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_type TEXT NOT NULL,          -- 'Pedido No Habitual' o 'Falta de Recolección'
    waste_type TEXT,                    -- Ej. 'escombros', 'poda', 'otros'
    quantity TEXT,                      -- Descripción de cantidad
    address TEXT NOT NULL,              -- Dirección proporcionada
    days_without_service NUMERIC,       -- Solo para reclamo de recolección
    chat_id TEXT NOT NULL,              -- Teléfono (ID de Manychat/Whatsapp)
    user_name TEXT,                     -- Nombre del vecino
    status TEXT DEFAULT 'Pendiente',    -- Estado actual del trámite ('Pendiente', 'Resuelto', etc)
    sla_deadline TIMESTAMP WITH TIME ZONE, -- Fecha límite de resolución según el SLA (ej. 72hs)
    live_chat_url TEXT,                 -- URL al live chat de Manychat para seguimiento manual
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para búsquedas de tickets por usuario
CREATE INDEX idx_tickets_chat_id ON public.tickets (chat_id);

-- 3. Tabla de Programas Ambientales (SE-PA-RÁ, E-DU-CÁ, CONTROLÁ)
CREATE TABLE public.program_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_type TEXT NOT NULL,         -- 'separa', 'educa', 'transforma', etc.
    institution_name TEXT,              -- Para educación ambiental
    address TEXT NOT NULL,              -- Dirección
    responsible_person TEXT,            -- Responsable institucional
    student_count NUMERIC,              -- Cantidad de alumnos
    chat_id TEXT NOT NULL,              -- Teléfono (ID de Manychat/Whatsapp)
    user_name TEXT,                     -- Nombre del vecino
    status TEXT DEFAULT 'Pendiente',    -- Estado ('Pendiente', 'Contactado', 'Cerrado')
    live_chat_url TEXT,                 -- URL al live chat de Manychat para seguimiento manual
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para búsquedas de programas por usuario
CREATE INDEX idx_program_requests_chat_id ON public.program_requests (chat_id);

-- ==============================================================
-- Opcional: Políticas de Seguridad (Restricciones RLS)
-- Si habilitas Row Level Security (RLS) en Supabase:
-- ==============================================================
-- ALTER TABLE public.chat_history ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.program_requests ENABLE ROW LEVEL SECURITY;

-- Permisos completos para el anon key y service root:
-- CREATE POLICY "Permitir todo a anon/service" ON public.chat_history FOR ALL USING (true);
-- (Misma política para tickets y program_requests si es necesario acceder directo desde el server via supabase-js anon)
